#!/usr/bin/env python3
"""
Compose modular Supabase assets into the root supabase workdir.

This is intended for a modular/microservice-style repo where platform and apps
own their own Supabase assets, while the current deployment target is a shared
Supabase instance.

Intended repo layout:

  supabase/                         # shared/composed Supabase workdir
    config.toml                     # committed; shared instance config
    migrations/                     # generated; do not edit directly
    seeds/                          # generated; do not edit directly
    functions/                      # generated; do not edit directly

  platform/supabase/migrations/     # platform-owned migration source
  platform/supabase/seeds/          # platform-owned seed source
  platform/supabase/functions/      # platform-owned function source

  apps/<app>/supabase/migrations/   # app-owned migration source
  apps/<app>/supabase/seeds/        # app-owned seed source
  apps/<app>/supabase/functions/    # app-owned function source

  db-packs/<pack>/supabase/...      # optional shared pack source

Usage through tools.py:

  python tools/tools.py compose_supabase
  python tools/tools.py compose_supabase --dry-run
  python tools/tools.py compose_supabase --apps scribeswell inventory
  python tools/tools.py compose_supabase --include-db-packs
  python tools/tools.py compose_supabase --no-functions
  python tools/tools.py compose_supabase --no-seeds

After composing:

  npx supabase db push --workdir supabase --local

For functions, deploy from the root/shared workdir, for example:

  npx supabase functions deploy cs-generate-signed-url --workdir supabase
  npx supabase functions deploy sw-process-document --workdir supabase

Notes:
- Root supabase/config.toml is NOT generated by this script.
- Function config blocks such as [functions.my-function] should live in the
  root supabase/config.toml for the shared instance.
- Migration timestamp prefixes must be globally unique across all composed modules.
- Function directory names must be unique across all composed modules.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Literal

# This file is expected at: repo/tools/py/run_compose_supabase.py
REPO_ROOT = Path(__file__).resolve().parents[2]
ROOT_SUPABASE_DIR = REPO_ROOT / "supabase"

OUTPUT_MIGRATIONS_DIR = ROOT_SUPABASE_DIR / "migrations"
OUTPUT_SEEDS_DIR = ROOT_SUPABASE_DIR / "seeds"
OUTPUT_FUNCTIONS_DIR = ROOT_SUPABASE_DIR / "functions"

MANIFEST_PATH = ROOT_SUPABASE_DIR / ".composed-manifest.json"
GENERATED_MARKER_FILE = ".generated-by-compose-supabase"

MIGRATION_RE = re.compile(r"^(?P<version>\d{14})_(?P<name>.+)\.sql$")
SeedMode = Literal["flat", "module-subdirs"]


@dataclass(frozen=True)
class Module:
    name: str
    path: Path

    @property
    def supabase_dir(self) -> Path:
        return self.path / "supabase"

    @property
    def migrations_dir(self) -> Path:
        return self.supabase_dir / "migrations"

    @property
    def seeds_dir(self) -> Path:
        return self.supabase_dir / "seeds"

    @property
    def functions_dir(self) -> Path:
        return self.supabase_dir / "functions"

    @property
    def repo_relative_path(self) -> str:
        return self.path.relative_to(REPO_ROOT).as_posix()


@dataclass(frozen=True)
class MigrationFile:
    version: str
    file_name: str
    source_path: Path
    module: Module

    @property
    def repo_relative_source(self) -> str:
        return self.source_path.relative_to(REPO_ROOT).as_posix()


@dataclass(frozen=True)
class SeedFile:
    file_name: str
    source_path: Path
    module: Module
    destination_relative_path: str

    @property
    def repo_relative_source(self) -> str:
        return self.source_path.relative_to(REPO_ROOT).as_posix()


@dataclass(frozen=True)
class FunctionDir:
    function_name: str
    source_path: Path
    module: Module

    @property
    def repo_relative_source(self) -> str:
        return self.source_path.relative_to(REPO_ROOT).as_posix()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compose modular Supabase migrations, seeds, and functions into root supabase/."
    )

    parser.add_argument(
        "--apps",
        nargs="*",
        default=None,
        help=(
            "Specific apps under apps/<name>/supabase to include. "
            "Default: include all apps that have a supabase folder."
        ),
    )

    parser.add_argument(
        "--include-db-packs",
        action="store_true",
        help="Also include db-packs/<name>/supabase if present.",
    )

    parser.add_argument(
        "--no-platform",
        action="store_true",
        help="Do not include platform/supabase.",
    )

    parser.add_argument(
        "--no-migrations",
        action="store_true",
        help="Do not compose migrations.",
    )

    parser.add_argument(
        "--no-seeds",
        action="store_true",
        help="Do not compose seeds.",
    )

    parser.add_argument(
        "--no-functions",
        action="store_true",
        help="Do not compose Edge Functions.",
    )

    parser.add_argument(
        "--seed-mode",
        choices=["flat", "module-subdirs"],
        default="flat",
        help=(
            "How to compose seeds. 'flat' copies all .sql seed files into supabase/seeds. "
            "'module-subdirs' copies to supabase/seeds/<module>/ and requires root config.toml "
            "sql_paths to include nested files. Default: flat."
        ),
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate and print the composition plan without writing files.",
    )

    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Alias for --dry-run; useful in CI validation jobs.",
    )

    parser.add_argument(
        "--no-clean",
        action="store_true",
        help=(
            "Do not delete existing generated SQL/files/directories before copying. "
            "Not recommended for normal use."
        ),
    )

    parser.add_argument(
        "--allow-empty",
        action="store_true",
        help="Do not fail when no assets are discovered.",
    )

    parser.add_argument(
        "--no-manifest",
        action="store_true",
        help="Do not write supabase/.composed-manifest.json.",
    )

    return parser.parse_args()


def has_supabase_assets(module_path: Path) -> bool:
    supabase_dir = module_path / "supabase"
    return any(
        (supabase_dir / child).exists()
        for child in ["migrations", "seeds", "functions"]
    )


def discover_modules(args: argparse.Namespace) -> list[Module]:
    modules: list[Module] = []

    if not args.no_platform:
        platform_path = REPO_ROOT / "platform"
        if has_supabase_assets(platform_path):
            modules.append(Module("platform", platform_path))

    apps_root = REPO_ROOT / "apps"
    if args.apps is None:
        if apps_root.exists():
            for app_path in sorted(p for p in apps_root.iterdir() if p.is_dir()):
                if has_supabase_assets(app_path):
                    modules.append(Module(app_path.name, app_path))
    else:
        for app_name in args.apps:
            app_path = apps_root / app_name
            if not has_supabase_assets(app_path):
                print(f"❌ App Supabase assets not found: {(app_path / 'supabase').relative_to(REPO_ROOT)}")
                sys.exit(1)
            modules.append(Module(app_name, app_path))

    if args.include_db_packs:
        packs_root = REPO_ROOT / "db-packs"
        if packs_root.exists():
            for pack_path in sorted(p for p in packs_root.iterdir() if p.is_dir()):
                if has_supabase_assets(pack_path):
                    modules.append(Module(f"db-pack:{pack_path.name}", pack_path))

    return modules


def collect_migrations(modules: Iterable[Module]) -> list[MigrationFile]:
    migrations: list[MigrationFile] = []

    for module in modules:
        if not module.migrations_dir.exists():
            continue

        for sql_file in sorted(module.migrations_dir.glob("*.sql")):
            match = MIGRATION_RE.match(sql_file.name)
            if not match:
                print(
                    f"❌ Invalid Supabase migration filename in {module.name}: "
                    f"{sql_file.relative_to(REPO_ROOT)}"
                )
                print("   Expected format: YYYYMMDDHHMMSS_description.sql")
                sys.exit(1)

            migrations.append(
                MigrationFile(
                    version=match.group("version"),
                    file_name=sql_file.name,
                    source_path=sql_file,
                    module=module,
                )
            )

    return sorted(migrations, key=lambda m: (m.version, m.file_name))


def collect_seeds(modules: Iterable[Module], mode: SeedMode) -> list[SeedFile]:
    seeds: list[SeedFile] = []

    for module in modules:
        if not module.seeds_dir.exists():
            continue

        # Keep deterministic order. Recursive supports module-specific seed subfolders if used.
        for seed_file in sorted(p for p in module.seeds_dir.rglob("*.sql") if p.is_file()):
            relative_inside_module = seed_file.relative_to(module.seeds_dir).as_posix()
            if mode == "flat":
                destination_relative_path = relative_inside_module
            else:
                safe_module_name = module.name.replace(":", "__")
                destination_relative_path = f"{safe_module_name}/{relative_inside_module}"

            seeds.append(
                SeedFile(
                    file_name=seed_file.name,
                    source_path=seed_file,
                    module=module,
                    destination_relative_path=destination_relative_path,
                )
            )

    return sorted(seeds, key=lambda s: (s.destination_relative_path, s.repo_relative_source))


def collect_functions(modules: Iterable[Module]) -> list[FunctionDir]:
    functions: list[FunctionDir] = []

    for module in modules:
        if not module.functions_dir.exists():
            continue

        for function_dir in sorted(p for p in module.functions_dir.iterdir() if p.is_dir()):
            # Skip common non-function utility folders if a team uses them.
            if function_dir.name.startswith("_") or function_dir.name in {"shared", "_shared"}:
                continue

            functions.append(
                FunctionDir(
                    function_name=function_dir.name,
                    source_path=function_dir,
                    module=module,
                )
            )

    return sorted(functions, key=lambda f: (f.function_name, f.repo_relative_source))


def validate_migrations(migrations: list[MigrationFile]) -> None:
    by_version: dict[str, list[MigrationFile]] = {}
    by_file_name: dict[str, list[MigrationFile]] = {}

    for migration in migrations:
        by_version.setdefault(migration.version, []).append(migration)
        by_file_name.setdefault(migration.file_name, []).append(migration)

    duplicate_versions = {k: v for k, v in by_version.items() if len(v) > 1}
    if duplicate_versions:
        print("❌ Duplicate Supabase migration version(s) found.")
        print("   Supabase treats the timestamp prefix as the migration version.")
        for version, items in duplicate_versions.items():
            print(f"\n   Version {version}:")
            for item in items:
                print(f"     - {item.repo_relative_source}")
        sys.exit(1)

    duplicate_filenames = {k: v for k, v in by_file_name.items() if len(v) > 1}
    if duplicate_filenames:
        print("❌ Duplicate migration filename(s) found.")
        for file_name, items in duplicate_filenames.items():
            print(f"\n   File {file_name}:")
            for item in items:
                print(f"     - {item.repo_relative_source}")
        sys.exit(1)


def validate_seeds(seeds: list[SeedFile]) -> None:
    by_destination: dict[str, list[SeedFile]] = {}
    for seed in seeds:
        by_destination.setdefault(seed.destination_relative_path, []).append(seed)

    duplicates = {k: v for k, v in by_destination.items() if len(v) > 1}
    if duplicates:
        print("❌ Duplicate seed destination path(s) found.")
        print("   Rename seed files or use --seed-mode module-subdirs.")
        for destination, items in duplicates.items():
            print(f"\n   Destination {destination}:")
            for item in items:
                print(f"     - {item.repo_relative_source}")
        sys.exit(1)


def validate_functions(functions: list[FunctionDir]) -> None:
    by_name: dict[str, list[FunctionDir]] = {}
    for function in functions:
        by_name.setdefault(function.function_name, []).append(function)

    duplicates = {k: v for k, v in by_name.items() if len(v) > 1}
    if duplicates:
        print("❌ Duplicate Edge Function name(s) found.")
        print("   Function names are global within a Supabase project.")
        for function_name, items in duplicates.items():
            print(f"\n   Function {function_name}:")
            for item in items:
                print(f"     - {item.repo_relative_source}")
        sys.exit(1)


def print_plan(
    modules: list[Module],
    migrations: list[MigrationFile],
    seeds: list[SeedFile],
    functions: list[FunctionDir],
    include_migrations: bool,
    include_seeds: bool,
    include_functions: bool,
) -> None:
    print("📦 Supabase composition plan")
    print(f"   Repo root: {REPO_ROOT}")
    print(f"   Root Supabase workdir: {ROOT_SUPABASE_DIR.relative_to(REPO_ROOT)}")

    print("\n   Modules:")
    if not modules:
        print("     - None")
    else:
        for module in modules:
            migration_count = len(list(module.migrations_dir.glob("*.sql"))) if module.migrations_dir.exists() else 0
            seed_count = len(list(module.seeds_dir.rglob("*.sql"))) if module.seeds_dir.exists() else 0
            function_count = len([p for p in module.functions_dir.iterdir() if p.is_dir()]) if module.functions_dir.exists() else 0
            print(
                f"     - {module.name}: {module.repo_relative_path} "
                f"({migration_count} migrations, {seed_count} seeds, {function_count} functions)"
            )

    if include_migrations:
        print(f"\n   Migrations to compose: {len(migrations)}")
        for migration in migrations:
            print(f"     - {migration.file_name}  <=  {migration.repo_relative_source}")
    else:
        print("\n   Migrations: skipped")

    if include_seeds:
        print(f"\n   Seeds to compose: {len(seeds)}")
        for seed in seeds:
            print(f"     - {seed.destination_relative_path}  <=  {seed.repo_relative_source}")
    else:
        print("\n   Seeds: skipped")

    if include_functions:
        print(f"\n   Functions to compose: {len(functions)}")
        for function in functions:
            print(f"     - {function.function_name}/  <=  {function.repo_relative_source}")
    else:
        print("\n   Functions: skipped")


def ensure_generated_marker(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    (directory / GENERATED_MARKER_FILE).write_text(
        "This directory is generated by tools/py/run_compose_supabase.py.\n"
        "Do not edit generated contents directly. Edit module-owned supabase assets instead.\n",
        encoding="utf-8",
    )


def clean_generated_dir(directory: Path, patterns: list[str] | None = None, remove_subdirs: bool = False) -> None:
    directory.mkdir(parents=True, exist_ok=True)

    if patterns:
        for pattern in patterns:
            for target in directory.glob(pattern):
                if target.name in {".gitkeep", GENERATED_MARKER_FILE}:
                    continue
                if target.is_file() or target.is_symlink():
                    target.unlink()
                elif target.is_dir() and remove_subdirs:
                    shutil.rmtree(target)
    elif remove_subdirs:
        for target in directory.iterdir():
            if target.name in {".gitkeep", GENERATED_MARKER_FILE}:
                continue
            if target.is_file() or target.is_symlink():
                target.unlink()
            elif target.is_dir():
                shutil.rmtree(target)

    ensure_generated_marker(directory)


def copy_migrations(migrations: list[MigrationFile]) -> None:
    for migration in migrations:
        shutil.copy2(migration.source_path, OUTPUT_MIGRATIONS_DIR / migration.file_name)


def copy_seeds(seeds: list[SeedFile]) -> None:
    ensure_generated_marker(OUTPUT_SEEDS_DIR)
    for seed in seeds:
        destination = OUTPUT_SEEDS_DIR / seed.destination_relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(seed.source_path, destination)


def copy_functions(functions: list[FunctionDir]) -> None:
    ensure_generated_marker(OUTPUT_FUNCTIONS_DIR)
    for function in functions:
        destination = OUTPUT_FUNCTIONS_DIR / function.function_name
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(
            function.source_path,
            destination,
            ignore=shutil.ignore_patterns("node_modules", ".git", ".DS_Store"),
        )


def write_manifest(
    modules: list[Module],
    migrations: list[MigrationFile],
    seeds: list[SeedFile],
    functions: list[FunctionDir],
    args: argparse.Namespace,
) -> None:
    payload = {
        "generatedAtUtc": datetime.now(timezone.utc).isoformat(),
        "repoRoot": str(REPO_ROOT),
        "rootSupabaseWorkdir": ROOT_SUPABASE_DIR.relative_to(REPO_ROOT).as_posix(),
        "options": {
            "includeMigrations": not args.no_migrations,
            "includeSeeds": not args.no_seeds,
            "includeFunctions": not args.no_functions,
            "seedMode": args.seed_mode,
            "includeDbPacks": args.include_db_packs,
            "includePlatform": not args.no_platform,
            "apps": args.apps,
        },
        "modules": [
            {
                "name": module.name,
                "path": module.repo_relative_path,
                "supabaseDir": module.supabase_dir.relative_to(REPO_ROOT).as_posix(),
            }
            for module in modules
        ],
        "migrations": [
            {
                "version": migration.version,
                "fileName": migration.file_name,
                "module": migration.module.name,
                "source": migration.repo_relative_source,
                "destination": f"supabase/migrations/{migration.file_name}",
            }
            for migration in migrations
        ],
        "seeds": [
            {
                "fileName": seed.file_name,
                "module": seed.module.name,
                "source": seed.repo_relative_source,
                "destination": f"supabase/seeds/{seed.destination_relative_path}",
            }
            for seed in seeds
        ],
        "functions": [
            {
                "functionName": function.function_name,
                "module": function.module.name,
                "source": function.repo_relative_source,
                "destination": f"supabase/functions/{function.function_name}",
            }
            for function in functions
        ],
    }
    MANIFEST_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    if args.check_only:
        args.dry_run = True

    if not ROOT_SUPABASE_DIR.exists():
        print(f"❌ Root Supabase folder not found: {ROOT_SUPABASE_DIR.relative_to(REPO_ROOT)}")
        print("   Expected a root supabase/config.toml for the shared Supabase instance.")
        sys.exit(1)

    include_migrations = not args.no_migrations
    include_seeds = not args.no_seeds
    include_functions = not args.no_functions

    modules = discover_modules(args)

    migrations = collect_migrations(modules) if include_migrations else []
    seeds = collect_seeds(modules, args.seed_mode) if include_seeds else []
    functions = collect_functions(modules) if include_functions else []

    if include_migrations:
        validate_migrations(migrations)
    if include_seeds:
        validate_seeds(seeds)
    if include_functions:
        validate_functions(functions)

    if not args.allow_empty and not migrations and not seeds and not functions:
        print("❌ No Supabase assets discovered. Use --allow-empty if this is intentional.")
        sys.exit(1)

    print_plan(
        modules,
        migrations,
        seeds,
        functions,
        include_migrations=include_migrations,
        include_seeds=include_seeds,
        include_functions=include_functions,
    )

    if args.dry_run:
        print("\n✅ Dry run complete. No files were changed.")
        return

    if include_migrations:
        if not args.no_clean:
            clean_generated_dir(OUTPUT_MIGRATIONS_DIR, patterns=["*.sql"])
        else:
            ensure_generated_marker(OUTPUT_MIGRATIONS_DIR)
        copy_migrations(migrations)

    if include_seeds:
        if not args.no_clean:
            clean_generated_dir(OUTPUT_SEEDS_DIR, patterns=["*.sql", "**/*.sql"], remove_subdirs=True)
        else:
            ensure_generated_marker(OUTPUT_SEEDS_DIR)
        copy_seeds(seeds)

    if include_functions:
        if not args.no_clean:
            clean_generated_dir(OUTPUT_FUNCTIONS_DIR, remove_subdirs=True)
        else:
            ensure_generated_marker(OUTPUT_FUNCTIONS_DIR)
        copy_functions(functions)

    if not args.no_manifest:
        write_manifest(modules, migrations, seeds, functions, args)

    print("\n✅ Supabase composition complete")
    if include_migrations:
        print(f"   Migrations: {len(migrations)} -> {OUTPUT_MIGRATIONS_DIR.relative_to(REPO_ROOT)}")
    if include_seeds:
        print(f"   Seeds:      {len(seeds)} -> {OUTPUT_SEEDS_DIR.relative_to(REPO_ROOT)}")
    if include_functions:
        print(f"   Functions:  {len(functions)} -> {OUTPUT_FUNCTIONS_DIR.relative_to(REPO_ROOT)}")

    print("\nNext commands:")
    print("  npx supabase db push --workdir supabase --local")
    print("  # deploy functions as needed, for example:")
    print("  npx supabase functions deploy <function-name> --workdir supabase")

    if args.seed_mode == "module-subdirs":
        print("\n⚠️  You used --seed-mode module-subdirs.")
        print("   Ensure supabase/config.toml has a db.seed.sql_paths pattern that includes nested files, e.g.:")
        print('   sql_paths = ["./seeds/**/*.sql"]')


if __name__ == "__main__":
    main()
