// Generated by apps/pts/tools/generate_contracts.py. Do not edit.
export type CollectionResponse = {schema_version: string;exported_at: string;note: string;poems: (Record<string, any>)[];witnesses: (Record<string, any>)[];sources: (Record<string, any>)[];rights: (Record<string, any>)[];source_documents: (Record<string, any>)[];total: number;collection_total: number;filters: Record<string, (string)[]>;citations: Record<string, string>;};
export type DocumentResponse = {status: 'stored' | 'link_only';url: string;expires_in?: number | null;document: Record<string, any>;};
export type HTTPValidationError = {detail?: (ValidationError)[];};
export type PoemResponse = {poem: Record<string, any>;evidence: Selection;citation: string;};
export type Selection = {schema_version: string;exported_at: string;note: string;poems: (Record<string, any>)[];witnesses: (Record<string, any>)[];sources: (Record<string, any>)[];rights: (Record<string, any>)[];source_documents: (Record<string, any>)[];};
export type ValidationError = {loc: (string | number)[];msg: string;type: string;};
