"""
Optional JWT verifier — generated by builder-cli.

Usage:
    # Public endpoint — user may or may not be signed in
    @router.get("/public")
    async def public_endpoint(user: OptionalUser = Depends(get_optional_user)):
        if user:
            return {"message": f"Hello {user['email']}"}
        return {"message": "Hello anonymous"}

    # Required endpoint — must be signed in
    @router.get("/private")
    async def private_endpoint(user: RequiredUser = Depends(get_required_user)):
        return {"message": f"Hello {user['email']}"}

Token format: Supabase-issued JWT in Authorization: Bearer <token>
"""
from typing import Annotated, Optional
import httpx
from starlette.concurrency import run_in_threadpool
from fastapi import Depends, Request
from jose import JWTError, jwt

from config import settings

ALGORITHM = "HS256"


def _extract_token(request: Request) -> Optional[str]:
    auth = request.headers.get("Authorization", "")
    if auth.startswith("Bearer "):
        return auth[7:]
    return None


def _decode_token(token: str) -> Optional[dict]:
    try:
        algorithm = jwt.get_unverified_header(token).get("alg")
        if algorithm == ALGORITHM:
            if not settings.supabase_jwt_secret:
                return None
            return jwt.decode(
                token, settings.supabase_jwt_secret, algorithms=[ALGORITHM],
                options={"verify_aud": False},
            )
        if algorithm not in {"ES256", "RS256"}:
            return None
        # Auth verifies signature, issuer and expiry against this configured project.
        # Never derive the verification endpoint from untrusted token claims.
        url = settings.supabase_url.rstrip("/")
        key = settings.supabase_anon_key
        if not url or not key:
            return None
        response = httpx.get(
            url + "/auth/v1/user",
            headers={"Authorization": "Bearer " + token, "apikey": key},
            timeout=5,
        )
        response.raise_for_status()
        claims = jwt.get_unverified_claims(token)
        # Claims are used only after Auth has accepted this exact token.
        actor = response.json().get("id")
        return claims if actor and claims.get("sub") == actor else None
    except (JWTError, httpx.HTTPError, ValueError, AttributeError):
        return None


async def get_optional_user(request: Request) -> Optional[dict]:
    """
    Dependency: returns decoded JWT payload if a valid token is present,
    otherwise returns None. Does NOT raise on missing/invalid token.
    """
    token = _extract_token(request)
    if not token:
        return None
    return await run_in_threadpool(_decode_token, token)


async def get_required_user(request: Request) -> dict:
    """
    Dependency: returns decoded JWT payload or raises 401.
    Use this for endpoints that require authentication.
    """
    from errors import UnauthorizedError

    token = _extract_token(request)
    if not token:
        raise UnauthorizedError("Authentication required")
    payload = await run_in_threadpool(_decode_token, token)
    if not payload:
        raise UnauthorizedError("Invalid or expired token")
    return payload


# Type aliases for cleaner endpoint signatures
OptionalUser = Annotated[Optional[dict], Depends(get_optional_user)]
RequiredUser = Annotated[dict, Depends(get_required_user)]
