const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
vm.runInThisContext(fs.readFileSync(process.argv[2],'utf8'));
const packet={items:[{id:'test',item_sha256:'abc',category:'imagery',summary:'Synthetic claim',kind:'analysis',alternatives:['Synthetic alternative']}]};
const state=new PtsReviewState(packet,'packet');
assert.equal(state.values.test.status,'pending');
assert.throws(()=>state.decisions(),/No decisions/);
assert.throws(()=>state.decide('test','approved'),/reviewer/);
state.reviewer='Synthetic reviewer';state.edit('test','category','custom_category');
state.edit('test','summary','Edited synthetic claim');
const saved=JSON.parse(JSON.stringify(state.work()));
const restored=new PtsReviewState(packet,'packet');restored.restore(saved);
assert.equal(restored.values.test.summary,'Edited synthetic claim');
assert.equal(restored.values.test.category,'custom_category');
assert.equal(restored.values.test.status,'pending');
restored.decide('test','approved');
assert.equal(restored.decisions().decisions[0].reviewer,'Synthetic reviewer');
const approved=JSON.parse(JSON.stringify(restored.work()));
state.restore(approved);assert.equal(state.values.test.status,'approved');
state.edit('test','summary','Another edit');assert.equal(state.values.test.status,'pending');
assert.throws(()=>state.decisions(),/No decisions/);
assert.throws(()=>state.decide('test','disputed'),/Explain/);
state.edit('test','notes','Synthetic disagreement');state.decide('test','disputed');
assert.equal(state.decisions().decisions[0].status,'disputed');
const before=JSON.stringify(state.work());
assert.throws(()=>state.restore({...saved,packet_sha256:'changed'}),/changed packet/);
assert.equal(JSON.stringify(state.work()),before);
assert.throws(()=>state.restore({...saved,items:[...saved.items,...saved.items]}),/Incomplete/);
assert.equal(JSON.stringify(state.work()),before);
console.log('Review state: save/restore, defaults, explicit approval, edit invalidation and stale-file protection passed.');
