create schema if not exists finance;

-- tables.ddl: SQL DDL for purchase and receipt tables (PostgreSQL/Supabase compatible)

CREATE TABLE IF NOT EXISTS finance.expense_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- multi-tenancy scope
    org_id uuid NOT NULL references identity.org(id) on delete restrict,
    name VARCHAR NOT NULL,
    description VARCHAR,
    deleted_at timestamptz DEFAULT NULL,
    created_by uuid references identity.users(id) on delete set null DEFAULT auth.uid(),
    created_at timestamptz DEFAULT now(),
    updated_by uuid references identity.users(id) on delete set null,
    updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_expense_category_org_id ON finance.expense_category (org_id);

-- Expense Type Table
CREATE TABLE IF NOT EXISTS finance.expense_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- multi-tenancy scope
    org_id uuid NOT NULL references identity.org(id) on delete restrict,
    expense_category_id BIGINT REFERENCES finance.expense_category(id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    description VARCHAR,
    deleted_at timestamptz DEFAULT NULL,
    created_by uuid references identity.users(id) on delete set null DEFAULT auth.uid(),
    created_at timestamptz DEFAULT now(),
    updated_by uuid references identity.users(id) on delete set null,
    updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_expense_type_org_id ON finance.expense_type (org_id);

-- Currency Table
CREATE TABLE IF NOT EXISTS finance.currency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- multi-tenancy scope
    org_id uuid NOT NULL references identity.org(id) on delete restrict,
    name VARCHAR NOT NULL,
    description VARCHAR,
    symbol VARCHAR,
    deleted_at timestamptz DEFAULT NULL,
    created_by uuid references identity.users(id) on delete set null DEFAULT auth.uid(),
    created_at timestamptz DEFAULT now(),
    updated_by uuid references identity.users(id) on delete set null,
    updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_currency_org_id ON finance.currency (org_id);

CREATE TABLE IF NOT EXISTS finance.receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- multi-tenancy scope
    org_id uuid NOT NULL references identity.org(id) on delete restrict,
    deleted_at timestamptz DEFAULT NULL,
    receipt_date date NOT NULL DEFAULT CURRENT_DATE,
    created_by uuid references identity.users(id) on delete set null DEFAULT auth.uid(),
    created_at timestamptz DEFAULT now(),
    updated_by uuid references identity.users(id) on delete set null,
    updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_receipt_org_id ON finance.receipt (org_id);

CREATE TABLE IF NOT EXISTS finance.purchase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT REFERENCES finance.receipt(id),
    expense_type_id BIGINT REFERENCES finance.expense_type(id),
    other_category VARCHAR,
    currency_id BIGINT REFERENCES finance.currency(id),
    user_id UUID REFERENCES auth.users(id),
    amount NUMERIC(1000,2) NOT NULL,
    reimbursable BOOLEAN NOT NULL,
    deleted_at timestamptz DEFAULT NULL,
    created_by uuid references identity.users(id) on delete set null DEFAULT auth.uid(),
    created_at timestamptz DEFAULT now(),
    updated_by uuid references identity.users(id) on delete set null,
    updated_at timestamptz DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_purchase_user_id ON finance.purchase(user_id);
CREATE INDEX IF NOT EXISTS idx_purchase_receipt_id ON finance.purchase(receipt_id);
CREATE INDEX IF NOT EXISTS idx_purchase_expense_type_id ON finance.purchase(expense_type_id);
CREATE INDEX IF NOT EXISTS idx_expense_type_category_id ON finance.expense_type(expense_category_id);

CREATE INDEX IF NOT EXISTS idx_purchase_created_by ON finance.purchase (created_by);
CREATE INDEX IF NOT EXISTS idx_receipt_created_by ON finance.receipt (created_by);
CREATE INDEX IF NOT EXISTS idx_expense_category_created_by ON finance.expense_category (created_by);
CREATE INDEX IF NOT EXISTS idx_expense_type_created_by ON finance.expense_type (created_by);
CREATE INDEX IF NOT EXISTS idx_currency_created_by ON finance.currency (created_by);

CREATE INDEX IF NOT EXISTS idx_purchase_updated_by ON finance.purchase (updated_by);
CREATE INDEX IF NOT EXISTS idx_receipt_updated_by ON finance.receipt (updated_by);
CREATE INDEX IF NOT EXISTS idx_expense_category_updated_by ON finance.expense_category (updated_by);
CREATE INDEX IF NOT EXISTS idx_expense_type_updated_by ON finance.expense_type (updated_by);
CREATE INDEX IF NOT EXISTS idx_currency_updated_by ON finance.currency (updated_by);

CREATE INDEX IF NOT EXISTS idx_receipt_receipt_date ON finance.receipt (receipt_date);

alter table finance.purchase enable row level security;
alter table finance.receipt enable row level security;
alter table finance.expense_category enable row level security;
alter table finance.expense_type enable row level security;
alter table finance.currency enable row level security;

-- Grants to the service role
GRANT USAGE ON SCHEMA finance TO service_role;  -- equivalent elevated role
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA finance TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA finance
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;

-- Grants to authenticated users (RLS policies control actual access)
-- Note: No DELETE permission - soft deletes via deleted_at timestamp only
-- Note: SELECT permission will be granted on views only (see policies migration)
GRANT USAGE ON SCHEMA finance TO authenticated;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA finance TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA finance
  GRANT INSERT, UPDATE ON TABLES TO authenticated;
