const {chromium}=require(process.argv[2] || 'playwright');
const fs=require('node:fs'), assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({headless:true,env:process.argv[3]?{...process.env,LD_LIBRARY_PATH:process.argv[3]}:process.env,args:['--no-sandbox','--disable-dev-shm-usage']});
 const page=await browser.newPage({viewport:{width:1500,height:1050},acceptDownloads:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',dialog=>dialog.accept());
 const url=`file://${root}/data/interim/guide-review-items-v2/psalms-23.html`;
 await page.goto(url);await page.waitForFunction(()=>document.querySelector('#source-image').naturalWidth>0);
 assert.equal(await page.locator('#item-list button').count(),20);
 await page.getByRole('button',{name:/Marked placement of/}).click();
 assert.equal(await page.locator('#category').inputValue(),'emphasis');
 await page.locator('#zoom').evaluate(el=>{el.value='150';el.dispatchEvent(new Event('input'));});
 assert.equal(await page.locator('#zoom-frame').evaluate(el=>el.style.width),'150%');
 await page.locator('#zoom').evaluate(el=>{el.value='100';el.dispatchEvent(new Event('input'));});
 assert.equal(await page.locator('#source-label').textContent(),'PDF page 22');
 assert.match(await page.locator('#evidence').textContent(),/Footnote 12/);
 await page.locator('#reviewer').fill('Synthetic browser test reviewer');
 await page.locator('#category').fill('synthetic_test_category');
 await page.locator('#summary').fill('SYNTHETIC BROWSER TEST ONLY — edited coherent claim.');
 let promise=page.waitForEvent('download');await page.locator('#save').click();await (await promise).saveAs('/tmp/pts-browser-work.json');
 await page.reload();await page.locator('#load-file').setInputFiles('/tmp/pts-browser-work.json');
 await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('restored'));
 await page.getByRole('button',{name:/Marked placement of/}).click();
 assert.equal(await page.locator('#category').inputValue(),'synthetic_test_category');
 assert.match(await page.locator('#summary').inputValue(),/SYNTHETIC BROWSER TEST/);
 await page.locator('#filter').selectOption('pending');await page.locator('#approve').click();
 assert.equal(await page.locator('#item-title').textContent(),'The transition from shepherd to host');
 assert.match(await page.locator('#progress').textContent(),/1 approved/);
 promise=page.waitForEvent('download');await page.locator('#export').click();await (await promise).saveAs('/tmp/pts-browser-decisions.json');
 const decisions=JSON.parse(fs.readFileSync('/tmp/pts-browser-decisions.json'));
 assert.equal(decisions.decisions.length,1);assert.match(decisions.decisions[0].id,/rod-staff-order/);
 await page.locator('#filter').selectOption('all');await page.getByRole('button',{name:/Marked placement of/}).click();
 await page.locator('#category').fill('emphasis');assert.match(await page.locator('#progress').textContent(),/0 approved/);
 await page.goto(url);await page.getByRole('button',{name:/Marked placement of/}).click();
 await page.screenshot({path:'/tmp/pts-review-desktop.png',fullPage:false});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/pts-review-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
 for(const [guide,count] of [['1',22],['133',15],['42-43',28]]){
   await page.goto(`file://${root}/data/interim/guide-review-items-v2/psalms-${guide}.html`);
   await page.waitForFunction(()=>document.querySelector('#source-image').naturalWidth>0);
   assert.equal(await page.locator('#item-list button').count(),count);
 }
 await page.setViewportSize({width:1500,height:1050});
 await page.goto(`file://${root}/data/interim/pts-studio-design-v1/index.html`);
 await page.waitForFunction(()=>document.querySelector('#image').naturalWidth>0);
 await page.screenshot({path:'/tmp/pts-studio-desktop.png',fullPage:false});
 await page.locator('#review-first').click();assert.match(await page.locator('#workspace').getAttribute('class'),/review-first/);
 await page.locator('#try-prompt').click();await page.locator('#language').selectOption('pt');
 assert.match(await page.locator('#prompt-text').textContent(),/Target language: Portuguese/);
 assert.match(await page.locator('#prompt-text').textContent(),/PROPOSALS ARE NOT APPROVED/);
 await page.screenshot({path:'/tmp/pts-studio-prompt.png',fullPage:false});
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Browser checks passed: four guides, image loading, category defaults, save/reload, explicit approval, filtered next, export, edit invalidation, mobile overflow, design layouts and language preview.');
})().catch(e=>{console.error(e);process.exit(1)});
