"""Generate the small reader's TypeScript DTOs from its Pydantic/OpenAPI boundary."""
import argparse
from pathlib import Path
from apps.pts.backend.main import app

def generate():
    schemas=app.openapi()['components']['schemas']
    def ts(s):
        if '$ref' in s:return s['$ref'].split('/')[-1]
        if 'enum' in s:return ' | '.join(repr(v) for v in s['enum'])
        if 'anyOf' in s:return ' | '.join(ts(v) for v in s['anyOf'])
        t=s.get('type')
        if t=='array':return '('+ts(s['items'])+')[]'
        if t=='object':
            if 'properties' in s:
                return '{'+''.join(f'{k}{"" if k in s.get("required",[]) else "?"}: {ts(v)};' for k,v in s['properties'].items())+'}'
            extra=s.get('additionalProperties',True)
            return 'Record<string, '+(ts(extra) if isinstance(extra,dict) else 'any')+'>'
        return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(t,'any')
    return '// Generated by apps/pts/tools/generate_contracts.py. Do not edit.\n'+''.join(f'export type {name} = {ts(schema)};\n' for name,schema in sorted(schemas.items()))

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    target=Path(__file__).parents[1]/'web/src/contracts.ts';result=generate()
    if args.check:
        if target.read_text()!=result:raise SystemExit('API contract drift')
    else:target.write_text(result)
